/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AxisX: typeof import('./components/charts/AxisX.vue')['default']
    AxisY: typeof import('./components/charts/AxisY.vue')['default']
    BarChart: typeof import('./components/charts/BarChart.vue')['default']
    BarCharts: typeof import('./components/BarCharts.vue')['default']
    BaseCanvas: typeof import('./components/charts/BaseCanvas.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    D3: typeof import('./components/charts/D3.vue')['default']
    DatasetPicker: typeof import('./components/DatasetPicker.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    LineChart: typeof import('./components/charts/LineChart.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    Selection: typeof import('./components/charts/Selection.vue')['default']
    Share: typeof import('./components/Share.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    SyncedCharts: typeof import('./components/charts/SyncedCharts.vue')['default']
    Toast: typeof import('./components/Toast.vue')['default']
    Toggle: typeof import('./components/Toggle.vue')['default']
    ToolTip: typeof import('./components/ToolTip.vue')['default']
  }
}
