/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./components/BarChart.vue')['default']
    BarCharts: typeof import('./components/BarCharts.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    DatasetPicker: typeof import('./components/DatasetPicker.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    Share: typeof import('./components/Share.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    Spinner: typeof import('./components/Spinner.vue')['default']
    Toggle: typeof import('./components/Toggle.vue')['default']
    ToolTip: typeof import('./components/ToolTip.vue')['default']
  }
}
